export default {
  sourceRoot: '_media-source',
  outputRoot: 'public/media/career',
  recipes: [
    {
      key: 'ira-vr',
      sourceFile: 'ira-vr/ira-vr.png',
      sourceId: '1bVfXRmZW6vDuHdsoSqEZOcM1gyOl4fI-',
      sourceUrl: 'https://drive.google.com/file/d/1bVfXRmZW6vDuHdsoSqEZOcM1gyOl4fI-/view',
      sourceLabel: 'IRA VR client learning view',
      status: 'public-corroborated',
      kind: 'image',
      alt: 'IRA VR learning module presented inside a panoramic immersive landscape',
      outputs: ['poster-640.webp', 'poster-1280.webp', 'poster-1280.avif'],
    },
    {
      key: 'machine-hunter-still',
      sourceFile: 'machine-hunter/machine-hunter.png',
      sourceId: '1OtHVjAJtq-FwszoUloCnld123LkvmUw5',
      sourceUrl: 'https://drive.google.com/file/d/1OtHVjAJtq-FwszoUloCnld123LkvmUw5/view',
      sourceLabel: 'Machine Hunter mixed-reality capture',
      status: 'internal-reference-only',
      kind: 'image',
      alt: 'Mixed-reality capture from the Machine Hunter virtual-reality game',
      outputs: [],
    },
    {
      key: 'machine-hunter',
      sourceFile: 'machine-hunter/machine-hunter.mp4',
      sourceId: '11fcukwZFUa42Ave95czc0izYyuhsdmxE',
      sourceUrl: 'https://drive.google.com/file/d/11fcukwZFUa42Ave95czc0izYyuhsdmxE/view',
      sourceLabel: 'Machine Hunter alpha video',
      status: 'public-corroborated',
      kind: 'video',
      alt: 'Gameplay excerpt from the Machine Hunter mixed-reality game',
      startSeconds: 56,
      durationSeconds: 6,
      width: 1280,
      height: 720,
      outputs: ['poster-640.webp', 'poster-1280.webp', 'clip.mp4', 'clip.webm'],
    },
    {
      key: 'oye-tippa-run',
      sourceFile: 'oye-tippa-run/oye-tippa-run.mp4',
      sourceId: '13Xzy9MMWwfXvgwpMLWR1z3H7WR-psPgk',
      sourceUrl: 'https://drive.google.com/file/d/13Xzy9MMWwfXvgwpMLWR1z3H7WR-psPgk/view',
      sourceLabel: 'Oye Tippa Run video',
      status: 'public-corroborated',
      kind: 'video',
      alt: 'Gameplay excerpt from Oye Tippa Run by the MysticMojo game studio',
      startSeconds: 38,
      durationSeconds: 6,
      width: 1280,
      height: 720,
      outputs: ['poster-640.webp', 'poster-1280.webp', 'clip.mp4', 'clip.webm'],
    },
    {
      key: 'celeste-ar',
      sourceFile: 'celeste-ar/celeste-ar.webp',
      sourceId: '1RdTNnMxeyCMUkAwx6gN-IStszfgMGq5t',
      sourceUrl: 'https://drive.google.com/file/d/1RdTNnMxeyCMUkAwx6gN-IStszfgMGq5t/view',
      sourceLabel: 'Celeste AR promotional still',
      status: 'public-corroborated',
      kind: 'image',
      alt: 'Fruit Masti augmented-reality game start screen from the Celeste AR work',
      outputs: ['poster-640.webp', 'poster-1280.webp', 'poster-1280.avif'],
    },
    {
      key: 'kave',
      sourceFile: 'kave/kave.jpg',
      sourceId: '15-9jurEjE4RfVD8Lnh7x3rpR9FRlvGe7',
      sourceUrl: 'https://drive.google.com/file/d/15-9jurEjE4RfVD8Lnh7x3rpR9FRlvGe7/view',
      sourceLabel: 'Kave collaboration-space still',
      status: 'internal-reference-only',
      kind: 'image',
      alt: 'Collaborative virtual workspace from the Kave platform exploration',
      outputs: [],
    },
  ],
};
